version: "3.8"

services:
  client:
    stdin_open: true
    container_name: client
    image: client
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: client
    ports:
      - "5050:80"
    volumes:
      - /app/node_modules
      - ./client:/app

  flask_api:
    stdin_open: true
    container_name: flask_api
    image: flask_api
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: flask_api
    ports:
      - "5000:5000"
